# Generated by Django 2.1.5 on 2019-02-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyCalendar_app', '0004_auto_20190225_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeupartist',
            name='artistId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
